# Generated by Django 2.0.7 on 2018-07-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='punto',
        ),
        migrations.AddField(
            model_name='punto',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='punto',
            name='physical_disabilities',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='punto',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='punto',
            name='sex',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
