# Generated by Django 2.1 on 2018-09-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='category',
            field=models.CharField(blank=True, default='None', max_length=42, null=True),
        ),
    ]
