# Generated by Django 2.1 on 2019-03-11 18:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0002_data_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStadistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('last_update', models.DateTimeField(default=datetime.datetime(2019, 3, 11, 18, 34, 9, 997534))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ('-id',)},
        ),
    ]
