# Generated by Django 2.0.7 on 2018-07-13 07:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0002_auto_20180713_0729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Punto',
            new_name='Point',
        ),
    ]
