# Generated by Django 2.0.7 on 2018-07-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20180713_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='physical_disabilities',
            new_name='ability',
        ),
        migrations.AddField(
            model_name='point',
            name='secuence',
            field=models.IntegerField(default=0),
        ),
    ]
