# Generated by Django 2.1 on 2019-03-11 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20190311_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstadistic',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 18, 35, 35, 498358, tzinfo=utc)),
        ),
    ]
