# Generated by Django 2.0.7 on 2018-07-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20180724_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='secuence_end',
            field=models.IntegerField(default=0),
        ),
    ]
