# Generated by Django 2.1 on 2019-03-11 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20190311_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstadistic',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
