# Generated by Django 2.1 on 2019-03-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20190311_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstadistic',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
