# Generated by Django 2.0.7 on 2018-08-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_point_secuence_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='ability',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='point',
            name='lat',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='point',
            name='lon',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='point',
            name='score',
            field=models.CharField(default='', max_length=1),
        ),
    ]
