# Generated by Django 2.0.7 on 2018-08-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20180803_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='lat',
            field=models.DecimalField(decimal_places=18, max_digits=20),
        ),
        migrations.AlterField(
            model_name='point',
            name='lon',
            field=models.DecimalField(decimal_places=18, max_digits=20),
        ),
    ]
