# Generated by Django 2.1 on 2019-03-11 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20190311_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstadistic',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 19, 30, 18, 456288, tzinfo=utc)),
        ),
    ]
