# Generated by Django 2.0.7 on 2018-08-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_auto_20180803_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='ability',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='point',
            name='score',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='point',
            name='sex',
            field=models.CharField(default='N', max_length=2),
        ),
    ]
