# Generated by Django 2.0.7 on 2018-08-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20180803_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='hdop',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='version',
            field=models.CharField(blank=True, default='0.0.1', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='point',
            name='lon',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
    ]
