# Generated by Django 2.0.7 on 2018-08-09 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_auto_20180809_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='observed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data', to='control.Observed'),
        ),
    ]
