# Generated by Django 2.0.7 on 2018-08-22 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0011_auto_20180809_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=2, null=True)),
                ('ability', models.CharField(blank=True, max_length=2, null=True)),
                ('version', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
